### ISSUE TITLE
Cordova Android Build

### ISSUE THREAD

**Issue by PeterA1** [jxcore/jxcore-cordova#1]
Hi,

I am using the standard Cordova HelloWorld project, with no changes for JXcore (other than the addition of the plugin).

Build process for Android went well, plugin added, tested, removed & added again.  Both time same result with Web Console giving the following 3 messages:-

TypeError: Cannot read property 'length' of null at file:///android_asset/www/cordova.js:914
deviceready has not fired after 5 seconds. at file:///android_asset/www/cordova.js:11169
Channel not fired: onJXcoreReady at file:///android_asset/www/cordova.js:1162

Looks like function androidExec() is being called with null args (the 5th Argument to the function).

Best Regards
Peter

**Comment by PeterA1** [comment]
Hi Again,

Added args = args || ""; at Line 912.  Project Builds, but no sign of jxcore app.js. (or window.cordova) after device ready.

Get messages of varying types including:-

PluginManager exec() call to unknown plugin: JXcore
or
Uncaught Reference Error: jxcore is node defined......(when using jxcore-cordova/sample)

Best Regards
Peter

**Comment by obastemur** [comment]
I'm working on Android part. Right now iOS side is up and running. Hopefully Android will be here very very soon! On which OS you were working on ?

**Comment by PeterA1** [comment]
Android ( 4.4.2 ), Let me know when you want someone to try on Android & I'll give it another spin.

**Comment by obastemur** [comment]
sure! I meant which OS you have on your PC ?

**Comment by PeterA1** [comment]
I'm on OSX.

**Comment by PeterA1** [comment]
I see you have https://github.com/obastemur/jxcore-android-basics, is this the Android initial release?

**Comment by obastemur** [comment]
latest commit adds Android support.

**Comment by Mithgol** [comment]
@obastemur

Thanks!

Would you continue changing the docs? After c7fb0c330dd77fb05276dde745366e6b505b9191 the file `README.md` [still says](https://github.com/jxcore/jxcore-cordova/blob/c7fb0c330dd77fb05276dde745366e6b505b9191/README.md) (in its section “[How to Install](https://github.com/jxcore/jxcore-cordova/blob/c7fb0c330dd77fb05276dde745366e6b505b9191/README.md#how-to-install)”) that “You need iOS binaries from JXcore” and contains instructions for building them. It probably also needs some alternative instructions for Android.

**Comment by obastemur** [comment]
@Mithgol for Android, you don't need to do anything. Everything is there! Perhaps I should add lots of inner details for at least 'how to update jxcore binaries inside'
