### ISSUE TITLE
Set fs_reach_sources to be false in Visual Studio

### ISSUE THREAD

**Issue by blissland** [jxcore/jxcore-cordova#102]
Hi,

I am using jxcore to build an app with visual studio (works great so far!). I have run into an issue where I need to set fs_reach_sources to be false. Any idea how to do this?

**Comment by ktrzeciaknubisa** [comment]
The `fs_reach_sources` option is a jx package feature, but the apps using jxcore-cordova plugin are not deployed as jx packages.

**Comment by blissland** [comment]
Ok thanks. I will find another workaround.
