### ISSUE TITLE
Error Adding Plugin

### ISSUE THREAD

**Issue by deefactorial** [jxcore/jxcore-cordova#11]
I went to test the latest changes today and now I get this when I add the plugin.
there is no package.json in that folder should there be ?

``` sh
cordova plugin add jxcore-cordova/io.jxcore.node/
Fetching plugin "jxcore-cordova/io.jxcore.node" via plugin registry
npm ERR! addLocal Could not install jxcore-cordova/io.jxcore.node
Error: ENOENT, open 'jxcore-cordova/io.jxcore.node/package.json'
    at Error (native)
```

**Comment by obastemur** [comment]
Interesting, it was never been there.What cordova version do you have ?

**Comment by deefactorial** [comment]
cordova --version
4.3.0

**Comment by deefactorial** [comment]
I build the project yesterday with no issues. I will try again from scratch.

**Comment by deefactorial** [comment]
by checking out the project again from scratch the plugin installed.

``` sh
cordova plugin add jxcore-cordova/io.jxcore.node/
Installing "io.jxcore.node" for android
```

Thanks

**Comment by obastemur** [comment]
I've just added package.json anyway. Thanks for pointing it out.

**Comment by deefactorial** [comment]
I think I was in the wrong folder when I executed the cordova plugin add command.
