### ISSUE TITLE
jx install package manager failing

### ISSUE THREAD

**Issue by Jeevsxp** [jxcore/jxcore-cordova#110]
Hi guys,

I am having trouble intalling the mbtiles package using:

sudo jx npm install mbtiles --autoremove "*.gz"

I keep getting:

Error: 404 response downloading https://nodejs.org/dist/v0.10.40/-v0.10.40.tar.gz

It should be downloading: https://nodejs.org/dist/v0.10.40/node-v0.10.40.tar.gz

I think this might be cased by the old version of npm that is being used npm: '1.4.14' 

Is there any way to update this? Or is there another way to get the package installed?

**Comment by obastemur** [comment]
Which version of jxcore you were using? `jx -jxv`

**Comment by Jeevsxp** [comment]
{ http_parser: '1.0',
  node: '0.10.40',
  jxcore: '0.3.0.7',
  v8: '3.14.5.9',
  sm: 0,
  embedded: { sqlite: '3.8.4.3' },
  ares: '1.9.0-DEV',
  uv: '0.10.36',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1p',
  npm: '1.4.14' }

**Comment by obastemur** [comment]
Can you delete the following folders;
- `~/.jx`
- `~/.node-gyp`

and retry ?

**Comment by Jeevsxp** [comment]
I did try this before, but it seemed to work this time, thx

**Comment by Jeevsxp** [comment]
Quick couple of questions:

Why are you using an old version of npm? and why does the installation of a package need to download node again?

**Comment by ktrzeciaknubisa** [comment]
> Why are you using an old version of npm?

This is because we needed to alter npm sources, and doing that for each new npm version takes time. But we do plan to switch to one of newer version at some point, though.

> and why does the installation of a package need to download node again?

It's probably triggered by downloaded package itself (install scripts etc.). Maybe it searches for a node, and when it's not already on platform (is it?) then it downloads again?

**Comment by Jeevsxp** [comment]
Ok thank you, great project btw

**Comment by ktrzeciaknubisa** [comment]
Thanks :)
