### ISSUE TITLE
Jxcore crash

### ISSUE THREAD

**Issue by ghost** [jxcore/jxcore-cordova#119]
Hello, 

I saw this issue in my application:

01-06 08:48:13.346: E/jxcore-log(13969): { [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo' }
01-06 08:48:13.346: A/libc(13969): ../deps/uv/src/unix/stream.c:1231: uv__read_start_common: assertion "uv__stream_fd(stream) >= 0" failed
01-06 08:48:13.346: A/libc(13969): Fatal signal 6 (SIGABRT) at 0x00003691 (code=-6), thread 13969 (va.hellocordova)

So, i tried to connect to server, then i catch error. But somehow error happened in uv library. Then my application stopped work.

I'm using jxcore-cordova 0.0.8  and Android 5.1.1.

**Comment by obastemur** [comment]
@mefffis can you share a bit more info ? device / code piece ?

**Comment by obastemur** [comment]
Closing the issue. Feel free to open it back with more information
