### ISSUE TITLE
Android: replace JXcore binaries for V8

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore-cordova#12]
Can we run cordova android app with V8 internals? I was attempting to do so, but I didn't succeed.

After I copy newly compiled android binaries:

``` bash
$ cp -rf jxcore_repo_path/out_android/android/bin/ my_cordova_app_path/jxcore-cordova/io.jxcore.node/src/android/jxcore-binaries/
```

and try to recompile .so files I get the following error:

``` bash
$ cd my_cordova_app_path/jxcore-cordova/io.jxcore.node/src/android/jni
$ ~/android-ndk-r10d/ndk-build

Android NDK: ERROR: /my_cordova_app_path/jxcore-cordova/io.jxcore.node/src/android/jni/Android.mk:mozjs: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /my_cordova_app_path/jxcore-cordova/io.jxcore.node/src/android/jni/../jxcore-binaries/libmozjs_arm.a exists  or that its path is correct   
/Users/nubisa_krzs/android-ndk-r10d/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
```

**Comment by obastemur** [comment]
Cons: 
- This requires a whole different compile file and storing the separate binaries from v8.  
- Totally different experience on iOS and Android
- Missing ES6 features
- Not suitable for Bytecode compilation

Advantages:
- fs.stat returns Objects although it's a function. (this is barely an advantage and we will be fixing it)
- Minor performance kick-in 
- Native modules ? (not realistic)  

IMHO; I don't see any advantage of forcing v8 into cordova plugin. SM is getting pretty stable.

**Comment by obastemur** [comment]
Let's remove 'Minor performance kick-in' from V8 advantages list. SpiderMonkey 10% faster with webkit's sunspider benchmarks. [Feel free to test by your own](https://github.com/obastemur/sunspider)
