### ISSUE TITLE
Cant install 0.1.0

### ISSUE THREAD

**Issue by Zeipt** [jxcore/jxcore-cordova#131]
jxc install 0.1.0 --force

Downloading: http://az836273.vo.msecnd.net/0.1.0/io.jxcore.node.jx
Attempt 3 / 3
Error status code: 404

or
Downloading: http://az836273.vo.msecnd.net/0.1.0/io.jxcore.node.jx
Attempt 3 / 3
Error status code: 504

**Comment by obastemur** [comment]
@Zeipt there was a small issue with the VM host. must be fixed now

**Comment by Zeipt** [comment]
Yes, already ok. Thanx!
