### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Zeipt** [jxcore/jxcore-cordova#132]
jxc install 0.1.0 --force
Downloading: http://az836273.vo.msecnd.net/0.1.0/io.jxcore.node.jx
Progress: Done
Extracting plugin package...
Command failed: `"/usr/local/bin/jx" io.jxcore.node.jx`:
Error: Command failed: /bin/sh -c "/usr/local/bin/jx" io.jxcore.node.jx
Segmentation fault

**Comment by ktrzeciaknubisa** [comment]
Probably your `jx -jxv` is not 0.3.1.0? Previous JXcore versions will have problems with new packaging format introduced recently.

**Comment by Zeipt** [comment]
Oh, yes, you're right. Sorry :) Closed.

**Comment by ktrzeciaknubisa** [comment]
No sorry needed. JXC should be more clever, so we're going to add an extra check. Thanks for bringing it in! :)

**Comment by ktrzeciaknubisa** [comment]
JXC has been updated on npmjs.com accordingly. If JXcore lower than 0.3.1.0 is found on the platform, then jxc will download the latest for itself.

**Comment by Zeipt** [comment]
Great! :)
