### ISSUE TITLE
jxc install error

### ISSUE THREAD

**Issue by kankanevzat** [jxcore/jxcore-cordova#134]
$ **jxc install**
Skipping the download, since file io.jxcore.node.jx already exists.
If you want to force downloading, use --force option.
Downloading: https://jxcore.s3.amazonaws.com/0310/jx_rh32v8.zip

Cannot download JXcore. Required version `0310` might not be supported for that platform: jx_rh32v8

> OS:  Fedora 23 workstation

**Comment by ktrzeciaknubisa** [comment]
JXcore binary is not available on RH/Fedora x32 (only x64 - see [downloads](http://jxcore.com/downloads/))  therefore `jxc` cannot download JXcore for your platform to extract `io.jxcore.node.jx` package.

**Comment by kankanevzat** [comment]
Thank you for helping. I'll install Fedora x64.
