### ISSUE TITLE
How to make the built-in sqlite3 support UTF8 encoding?

### ISSUE THREAD

**Issue by AlexZhouAA** [jxcore/jxcore-cordova#138]
This should be a significant issue since there're people who need store Chinese, Japanese or Korean information in sqlite db. Unfortunately, if they do so, they'll retrieve scrambled characters when query from database.

And I found #107 where @ktrzeciaknubisa says jx V8 works OK without this issue.
I followed the instructions at https://github.com/jxcore/jxcore/blob/master/doc/Android_Compile.md#compile-as-a-static-library and https://github.com/jxcore/jxcore-cordova#updating-jxcore-binaries-optional 
The process was pretty smooth before I tried to recompile .so files.
 I got error as below,

<pre>
Android NDK: ERROR:/home/zhou/Downloads/jxcore-cordova/src/android/jni/Android.mk:mozjs: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /home/zhou/Downloads/jxcore-cordova/src/android/jni/../jxcore-binaries/libmozjs_arm.a exists  or that its path is correct   
/home/zhou/Downloads/androidNDK/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
</pre>

Then, I found #12. I can tell currently I can't replace JXcore binaries from sm to v8.

So now,  what can I do to make the built-in sqlite3 support UTF8 encoding?
It's essential to my project. Is there any other way to deal this?

Thanks in advance.

**Comment by ktrzeciaknubisa** [comment]
> Then, I found #12. I can tell currently I can't replace JXcore binaries from sm to v8.

Indeed, currently only SM can be used with jxcore-cordova

> So now, what can I do to make the built-in sqlite3 support UTF8 encoding?

Right now probably the best way for you would be e.g. to encode base64 data before putting into database an decode while reading.

**Comment by AlexZhouAA** [comment]
Thanks, I'll try that.

**Comment by voxsoftware** [comment]
Este módulo que hice soluciona el problema. Simplemente se llama
require("sqlite-mobile-fix"); después de require("sqlite")  y listo.
Saludos

2016-02-15 16:21 GMT-05:00 AlexZhouAA notifications@github.com:

**Comment by jhernancanom** [comment]
Hello, friends.
I am interested in info about SQLite3 and UTF8.
Where can I find _**sqlite-mobile-fix**_ for reading and understanding the solution?
Thanks.
