### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by quanganh206** [jxcore/jxcore-cordova#149]
Hi @obastemur, 

May I know about project's status, is it still running? Longtime have no update.

Regards./.

**Comment by ktrzeciaknubisa** [comment]
@quanganh206 Please check [Important Notice](https://github.com/jxcore/jxcore#important-notice) on jxcore. It applies to jxcore-cordova too.

**Comment by quanganh206** [comment]
Thanks @ktrzeciaknubisa !
