### ISSUE TITLE
Please move the location of app.js and related files

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore-cordova#16]
**Executive Summary:** The current plugin layout makes it impossible to upgrade the plugin without deleting user code.
## Long Winded Version:

When updating the jxcore-cordova plugin the safest way to do it is to remove the existing plugin and install the new version.

But jxcore-cordova keeps both its plugin code and the user's code under io.jxcore.node.

So if one uninstalls the plugin then one also deletes one's own code!

When we faced a similar problem in the past the way we solved it was by creating two directories when our plugin was installed. One directory contained our plugin code and the other directory contained the user's code. That way when our plugin was updated only the directory with the plugin code got deleted, not the directory with the user's code.

The way we made this work was by sort of "hiding" the user code directory from Cordova. We added to our plugin.xml:

``` xml
<hook type="after_plugin_add" src="scripts/appAfterPluginInstall.js"/>
```

You can see the appAfterPluginInstall.js file [here](https://gist.github.com/yaronyg/3ae3a49d38e0450fdd66)

The problem now was, how do we get the user's content from the NodeServices directory into the right location to be built for their platform? In the case of android we need the content put into assets. The way we handled that in the case of Android was via a Gradle file. We built a Gradle file that copied the contents to the right place. To get the gradle file called we added the following to our plugin.xml:

``` xml
<plugin>
   ...
   <platform name="android">
      ...
      <framework src="src/android/OurGradleFile.gradle" custom="true" type="gradleReference"/>
   </plaftorm>
</plugin>
```

This uses a feature documented [here](https://cordova.apache.org/docs/en/edge/guide_platforms_android_tools.md.html) that lets us add our own gradle logic programmatically to the main build.gradle.

I only had to do this work on Android so I have no clue what the equivalent is for iOS.

I know this is all a pain. But it's a pain that leaves your users in a situation where they can update the plugin without losing their source code! That seems like an important feature to me.

And I make no representations that the series of hacks above is the right way to solve this problem. It's just what we ended up with when we faced this issue, but keep in mind that none of the people involved in creating the Rube Goldbergesque nightmare above were actually Cordova experts.

**Comment by obastemur** [comment]
@yaronyg thanks for all the details. This is definitely an issue and going to fix it soon.

**Comment by deefactorial** [comment]
@yaronyg thanks for bringing up this issue. I think there can be a better way too.

What if the users code was in the www directory? 
the client side code is already in this directory but there is no conflict with the index.html file With the app.js file.

I think the long term javascript web application trend is towards isomorphic javascript applications where the client and the server share common logic. Having them both in a common folder enables them to share code easier than if they are seperate.

If the developer wanted a seperation of logic they could create a server and client folder. In the www directory and redirect the index.html to the client folder and rediect the app.js to the server folder.

**Comment by ktrzeciaknubisa** [comment]
> Executive Summary: The current plugin layout makes it impossible to upgrade the plugin without deleting user code.

I agree with all of you, updating the user code is tricky. However I've found for myself a way to update the code without removing/re-adding the plugin. Maybe someone will find this useful until there will be a better way.

For Android cordova app, if you are using Eclipse and have imported project by pointing `/my/cordova/app/platforms/android/` (and you don't intend to call cordova commands manually in shell), you can edit files located under `./platforms/android/assets`. Eclipse shows this just as `assets`. Well, the `./www` folder might be invisible. In such case probably you have `_where-is-www.txt` file with some note inside. Disabling the filter worked for me.

Beware, manually calling cordova commands (`build`/`run` etc.) will overwrite `index.html` (as it recreates entire `platforms/assets/www`). In that case it's better to edit files under `/my/cordova/app/www`. As for the `platforms/assets/jxcore` folder - it stays intact even with manual cordova commands.

**Comment by obastemur** [comment]
Actually, I'm just going to remove copying jxcore folder. This will be becoming an initial only installation step. **Create the `jxcore` folder under `www`**
