### ISSUE TITLE
Calling client's methods by server

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore-cordova#2]
I'm not sure why this happens, but when I add a second line at the top of _Resources/jxcore_app/app.js_ 

``` js
cordova('log').call("JXcore is up and running!");
cordova('log').call("Second");
```

The "Second" will not get displayed on client's side (nor any other subsequent call of "log").

I registered another client's method `log2()`, which does exactly the same as `log()` and it suffers the same problem - both of them seem to work only for the first time.

**Comment by obastemur** [comment]
Fixed. https://github.com/jxcore/jxcore-cordova/commit/73c7da0adfefb4874e5e21695d1c23d81154e97d
