### ISSUE TITLE
Template engine not working on Android

### ISSUE THREAD

**Issue by JoeKan** [jxcore/jxcore-cordova#23]
I tried to use handlebars render engine with express using express-handlebars module after fixing the fs.stat related issues. Executing this doesn't work:

```
var exphbs  = require('express-handlebars');
app.engine('handlebars', exphbs({defaultLayout: 'main'}));
app.set('view engine', 'handlebars');
app.get('/',function(req,res){
  res.render('home');    //home.handlebars using main.handlebars layout in ./views folder
});
```

The return error both on logcat and the browser:

```
@native:jxcore_js_object:3:12
```

This code works on iOS flawlessly.

**Comment by obastemur** [comment]
@JoeKan I didn't use handlebars before, do I need anything else apart from the code piece you have shared?

**Comment by JoeKan** [comment]
You need the express-handlebars module "npm install [express-handlebars](https://github.com/ericf/express-handlebars)"
and have this structure for the views:

```
├── app.js
└── views
    ├── home.handlebars
    └── layouts
        └── main.handlebars

```

This a sample for main.handlebars:

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Example App</title>
</head>
<body>

    {{{body}}}

</body>
</html>
```

This a sample for home.handlebars:

```
<h1>Example App: Home</h1>
```

And the sample code in the first comment and express module of course.

**Comment by obastemur** [comment]
This issue is related to https://github.com/jxcore/jxcore/issues/275 . UglifyJS's initial one by one context execution doesn't play well with optimized VM (vice versa). Prioritizing the issue. I'm now working on it.

**Comment by obastemur** [comment]
This should be properly working now. Thanks for all the details
