### ISSUE TITLE
Android: sample app fails on one of my devices

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jxcore/jxcore-cordova#26]
Device: **Alcatel OneTouch Evo7, ARMv7 Processor rev 2 (v7l), Android 4.0 (non-rooted)**

I've tried to run cordova sample app on it, and it crashes. It is related with signing up for `jxcore.isReady()` event (_index.html_);
- If I **don't** sign-up, the app interface loads correctly (but obviously without _app.js_ being loaded)
- If I **do** sign-up, even with an empty callback, like;

``` js
      jxcore.isReady(function(){
        alert("ok");
      });
```

Then it crashes. LogCat:

``` bash
05-18 16:46:16.159: W/jxcore-log(2224): Initializing JXcore engine
05-18 16:46:16.159: W/jxcore-log(2224): JXcore engine is ready
05-18 16:46:16.189: W/jxcore-log(2224): Starting JXcore engine
05-18 16:46:16.289: A/libc(2224): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1)
```

**Comment by JoeKan** [comment]
I used to have the same error on HTC One x+,tegra ARM based processor, running Android 4.2.2 official ROM non-rooted.
I flashed the device with CyanogenMod 11 Android 4.4.4 and the sample runs fine now. Is it really an ARM issue?

**Comment by obastemur** [comment]
@JoeKan this is indeed an OS issue that happens on some ARM chipsets. I'm still not able to reproduce the problem on my end. @ktrzeciaknubisa maybe you should hand me that device for a while :)

**Comment by obastemur** [comment]
@ktrzeciaknubisa I assume this was related to native stack size fix for Windows. Let's see if this also fixed

**Comment by ktrzeciaknubisa** [comment]
Right now it I'm not able to run jxcore-cordova project at all on this particular device, even with original `index.html` from cordova, which is supposed to display "Apache Cordova / Device is Ready" (so I'm not even using sample folder with `jxcore.isReady()` etc.). The error stays the same:

``` bash
06-09 13:38:33.366: W/jxcore-log(3381): Initializing JXcore engine
06-09 13:38:33.366: W/jxcore-log(3381): JXcore engine is ready
06-09 13:38:33.396: W/jxcore-log(3381): Starting JXcore engine
06-09 13:38:33.516: A/libc(3381): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1)
```

**Comment by ghost** [comment]
I run  the app in Android 5.0.1 emulator and it runs without a problem.I fixed javascript errors inside four modules( depd,qs,send,serve-static) after that the app runs without  a problem.

**Comment by obastemur** [comment]
This issue is fixed.
