### ISSUE TITLE
express.Router -solved

### ISSUE THREAD

**Issue by JimSEOW** [jxcore/jxcore-cordova#30]
In app.js

==> This works
app.get('/', function (req, res) {
  res.send('Hello World! (' + Date.now() + ")");
  clog("Request", req.headers['x-forwarded-for'] || 
      req.connection.remoteAddress || 
      req.socket.remoteAddress ||
      req.connection.socket.remoteAddress, new Date());
});

==> This does not work
app.get('/get', function (req, res) {
    res.send('Hello Get1! (' + Date.now() + ")");
});

I am trying to do test the method post

app.post('/post', function (req, res) {
        if (req.method == 'POST') {
            var jsonString = '';
            req.on('data', function (data) {
                jsonString += data;
            });
            req.on('end', function () {
                 var result = JSON.parse(jsonString);
                 clog(result);
                 cordova('addPost').call(result);
            });
        }
});

in index.js

  var addPost = function(postData) {
    document.getElementById('postID').innerHTML += postData  + "<BR/>";
  }

in index.html

<p id='postID'></p>

can someone please show a working example?

**Comment by ktrzeciaknubisa** [comment]
Can we have some update on what was the solution?

**Comment by JimSEOW** [comment]
There was another older version [different name](unkilled) capturing the server request. Once I kill all, it functions normal again.
