### ISSUE TITLE
Need a way to unregister functions

### ISSUE THREAD

**Issue by lastmjs** [jxcore/jxcore-cordova#32]
It would be nice to have a way to unregister functions as well. I've found the need to register functions dynamically, and I'm pretty sure I'm going to run into memory issues as my number of registered functions increases potentially infinitely.

**Comment by lastmjs** [comment]
It turns out this is not as important to me as I thought it was, and the problem I thought I was having (registering a function twice breaking the system) might not even be a problem. But being able to unregister functions might still be useful.

**Comment by obastemur** [comment]
The quickest approach could be preventing the double registration of named functions.
