### ISSUE TITLE
repo size ? 

### ISSUE THREAD

**Issue by smolleyes** [jxcore/jxcore-cordova#33]
hi

adding the plugin now takes age :p normal to have so much data?

https://api.github.com/repos/jxcore/jxcore-cordova

size: 200952 Oo

200 mo ?

thanks

**Comment by obastemur** [comment]
@smolleyes It has all the required binaries for both iOS and Android (ARM, intel). Perhaps it can be much smaller but you end up doing some additional steps. 

200Mb may not be that big considering all the targets and platforms supported. This is a developer package. For example, Android SDK alone takes up to 20 Gb :)

**Comment by obastemur** [comment]
You are adding it only once though. Right?
