### ISSUE TITLE
Android: Eclipse Problem with Android SDK 22.

### ISSUE THREAD

**Issue by ghost** [jxcore/jxcore-cordova#39]
I have followed the steps from README and successfully installed jxcore cordova plugin. The sample application works just fine. However, I wanted to import it into Eclipse and I saw there were lots of errors.

Seems like the problem was I don't have Android SDK 22 is installed. So I needed to change the value under androidmanifest.xml from 22 to 21(the one I have it on my local) and then recompiled CordovaLib project on eclipse.

This information can be helpful to others but I don't know where to document it. So I thought this is the right place.

**Comment by ghost** [comment]
Since there is no problem left to fix. I'm just closing this issue.

**Comment by ktrzeciaknubisa** [comment]
Thank you for sharing!
