### ISSUE TITLE
JX_InitializeNewEngine

### ISSUE THREAD

**Issue by Zeipt** [jxcore/jxcore-cordova#4]
> W/jxcore-log(23776): (JX_InitializeNewEngine) Did you forget destroying the existing JXEngine instance for this thread?
> E/jxcore-log(23776): You can set only 1 entry file per engine instance. You've already set main.js

This happens after exiting from my app (needs to click twice Back on Android) and starting app again.
How do destroy JXEngine instance correctly?

**Comment by obastemur** [comment]
I'm working on some improvements with the actual cordova interface. Could you please give me some more details on this problem so I can fix it?

**Comment by Zeipt** [comment]
Well, I use your Sample as base, added http server in it's app.js and loading my page from this server in Android's WebView. To exit app I need first click standard Android's Back softbutton. It results in closing WebView with my page and showing your Sample again. After second Back it closes. But Process continues and when I try to start app again I get those warn and error in adb-console.

**Comment by ktrzeciaknubisa** [comment]
Well, even without altering the original sample this can be reproduced. After the app is launched, when I exited with `back` button (just once is enough) and tapped the _HelloWorld_ icon on device screen to run the app again - it never displays (black screen for a few seconds and then exit).

LogCat says this:

``` bash
E/jxcore-log(22347): You can set only 1 entry file per engine instance. You've already set main.js
W/jxcore-log(22347): Starting JXcore engine
A/libc(22347): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 22347 (m.example.hello)
```

Starting an app afterwards (this would be a **3rd time**) - works.

**Comment by obastemur** [comment]
The original issue is fixed, however there will be improvements in order to prevent a similar scenario happening. Thanks for the details
