### ISSUE TITLE
callnative with one argument in jxcore.js is causing cordova failures

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore-cordova#42]
In jxcore.js there are calls like [this](https://github.com/jxcore/jxcore-cordova/blob/0614a42f4a46595a2aefe3da962219f3e29fdfe6/www/jxcore.js#L167) and [this](https://github.com/jxcore/jxcore-cordova/blob/0614a42f4a46595a2aefe3da962219f3e29fdfe6/www/jxcore.js#L173) where callNative is called with a single argument.

That makes cordova unhappy.

The reason is that callNative calls exec who eventually calls androidExec in cordova.js and specifically [this line](https://github.com/apache/cordova-android/blob/61df5e0a373e665201d46fb8125683cf621b2440/bin/templates/project/assets/www/cordova.js#L930). This line expects that args is an array.

But the callNative examples I give above don't pass in an args value and callNative accepts this undefined argument and blindly passes it to exec who gives it to androidExec who then causes an "uncaught TypeError: Cannot read property 'length' of null" exception.

Can you please put in a check for null args and set them to an empty array so we don't have to deal with this exception?

**Comment by ktrzeciaknubisa** [comment]
How about now, with the commit above?

**Comment by obastemur** [comment]
LGTM. Thanks @yaronyg @ktrzeciaknubisa
