### ISSUE TITLE
Windows: git clone long path name issue

### ISSUE THREAD

**Issue by obastemur** [jxcore/jxcore-cordova#43]
express sample project under sample folder gives long path name error when cloning this repository on a Windows computer. We might 'jx' package the node-modules folder or whole application to get rid of this problem.

Also this may sample jx package usage on mobile.

**Comment by ktrzeciaknubisa** [comment]
> when cloning this repository on a Windows computer.

Do you mean during `git clone` command? I don't receive this with `git --version` 1.9.5

**Comment by ktrzeciaknubisa** [comment]
I was able to successfully clone and compile jxcore-cordova (Windows 7, cordova 4.3.0) and run both express samples on Android. The long path name error never occurred.

**Comment by Robin-Svenhard** [comment]
The user can simply set git to handle long paths with the following command:

> git config core.longpaths true

**Comment by obastemur** [comment]
@Robin-Svenhard can you add (PR) that information into README.md of this repo?
