### ISSUE TITLE
Are native calls also single threaded?

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore-cordova#45]
I just wanted to double check something. The docs clearly say that when calling back from native code into JXCore one should do the callback on the same thread that one received the original call because JS is single threaded.

But are there any guarantees in iOS and Android that all call outs from Javascript will always go to the same thread?

In other words, imagine I have Mobile('foo').registerToNative(...

Am I guaranteed that if the JS calls the 'foo' function 10 times in a row that all 10 calls will be executed in the native language on the same thread?

**Comment by yaronyg** [comment]
Oh and a related question. Is the thread that the native call made on the same thread that the engine is running on? In other words if we get a native call and the native code does some expensive synchronous work will the node engine then be blocked?

**Comment by plika** [comment]
> I just wanted to double check something. The docs clearly say that when calling back from native code into JXCore one should do the callback on the same thread that one received the original call because JS is single threaded.

JXcore's Java and Objective-C interface makes sure the calls will be running under the JS engine thread. So, this is no issue. 

> In other words if we get a native call and the native code does some expensive synchronous work will the node engine then be blocked?

Yes. You should async native logic whenever it is possible. Moreover, there is no reason to keep JS engine thread on mobile though. JX-NI doesn't support sync function return from native land.

**Comment by obastemur** [comment]
> Am I guaranteed that if the JS calls the 'foo' function 10 times in a row that all 10 calls will be executed in the native language on the same thread? 

Yes

**Comment by yaronyg** [comment]
Thanks that clarifies things. Amongst other things it shows that all our native code have to be multi-thread safe since they need to run on separate threads from the JXCore thread for perf reasons. But it does argue that if we want we can do some pretty ugly things in terms of setting flag states since we know that all calls out from JXCore will start on the same thread. I suspect taking advantage of that is probably a bad idea and we would be better off just writing thread safe code that assumes arbitrary concurrency.

**Comment by obastemur** [comment]
That's a very clever trick though. I was using it before and this approach makes things a lot easier. 

We can not reach JS API from a thread that we didn't initialize the JS engine at the first place. However, I agree with you on that better not interfere with JXcore's JS thread.
