### ISSUE TITLE
res.sendFile() and express.static() error on Android. works on iOS.

### ISSUE THREAD

**Issue by JoeKan** [jxcore/jxcore-cordova#5]
//using express 4.12.3 and cordova 5.0.0
Writing this simple segment of code doesn't work:
var http = require('http');
var express = require('express');
var app = express();
var server = http.createServer(app);
server.listen(1337);
app.get('/',function(req,res){
    res.sendFile(__dirname + '/public/index.html');
    res.end();
});

The return error is:
5611-5648/com.example.hello E/jxcore-log﹕ etag@/data/data/com.example.hello/files/node_modules/express/node_modules/etag/index.js:55:1
setHeader@/data/data/com.example.hello/files/node_modules/express/node_modules/send/index.js:739:15
 SendStream.prototype.send@/data/data/com.example.hello/files/node_modules/express/node_modules/send/index.js:507:3   onstat@/data/data/com.example.hello/files/node_modules/express/node_modules/send/index.js:600:5
makeCallback/<@fs.js:83:12
fs.stat@fs.js:718:7    sendFile@/data/data/com.example.hello/files/node_modules/express/node_modules/send/index.js:590:3
SendStream.prototype.pipe@/data/data/com.example.hello/files/node_modules/express/node_modules/send/index.js:479:3
sendfile@/data/data/com.example.hello/files/node_modules/express/lib/response.js:1029:3
sendFile@/data/data/com.example.hello/files/node_modules/express/lib/response.js:402:3
@/data/data/com.example.hello/files/app.js:24:5
handle@/data/data/com.example.hello/files/node_modules/express/lib/router/layer.js:82:5
next@/data/data/com.example.hello/files/node_mod

However, this code works fine:
//using fs module
fs.readFile(__dirname + '/public/index.html',function(err,html){
       app.get('/',function(req,res){
           res.write(html);
           res.end();
      });
});

Tested on Android Studio and eclipse on both Linux Mint and Windows 7.

**Comment by JoeKan** [comment]
@obastemur can you please let me know the cause of this odd behavior by the plugin? Thanks

**Comment by obastemur** [comment]
@JoeKan this is an expected problem on Android and we will be fixing it soon.

**Comment by deefactorial** [comment]
I'm running into the same issue with my project.

if I log the __dirname value I get

``` js
console.log("__dirname", __dirname);
```

__dirname /data/data/com.openmoney.p2p/files

but when I check out what's in the folder there is nothing

``` sh
adb shell
run-as com.openmoney.p2p
cd /files
ls
```

This should be pointing to the assets/jxcore/ folder.
a quick search on how to read the assets folder (http://stackoverflow.com/questions/8474821/how-to-get-the-android-path-string-to-a-file-on-assets-folder) reveals that the assets are located in the APK.

So what's the best method to resolve this issue. Extract the APK assets into the /data/data/com.openmoney.p2p/files directory ?

**Comment by obastemur** [comment]
Number of access methods to files under APK are limited for now. You can require, or call readFileSync, existsSync on the target folder. Rest of the fs support for Android APK is on the way. Ping @ktrzeciaknubisa

**Comment by obastemur** [comment]
Quick note I've just pushed latest JXcore binaries with 'readdir' and 'readdirSync' support for APK.

**Comment by deefactorial** [comment]
@obastemur Awesome, I'll test them out,

**Comment by deefactorial** [comment]
I'm still getting the same error on readdir syscall:

``` js
loadMainFile { [Error: ENOENT, no such file or directory '/data/data/com.openmoney.p2p/files/node_modules/rendr/server/middleware']
    message: 'ENOENT, no such file or directory \'/data/data/com.openmoney.p2p/files/node_modules/rendr/server/middleware\'',
    errno: 34,
    code: 'ENOENT',
    path: '/data/data/com.openmoney.p2p/files/node_modules/rendr/server/middleware',
    syscall: 'readdir' }
```

**Comment by deefactorial** [comment]
I'm guessing the function assetReadDirSync in src/android/jni/jxcore.cpp needs to be implemented.

**Comment by obastemur** [comment]
`I'm guessing the function assetReadDirSync in src/android/jni/jxcore.cpp needs to be implemented.`
@deefactorial no, there is no need for special implementation. I will try to reproduce it the problem.

**Comment by deefactorial** [comment]
I just noticed something...

```
console.log("userPath", fs.readdirSync(process.userPath));
```

returns:
userPath [ 'jxcore' ] 

This means the readdirSync function works but the result is not what's expected. 
process.userPath should probably point to /data/data/com.openmoney.p2p/files/jxcore/

**Comment by obastemur** [comment]
You have __dirname equals to `/data/data/com.openmoney.p2p/files/jxcore/` and process.userPath ?

**Comment by deefactorial** [comment]
no they are:

```
__filename /data/data/com.openmoney.p2p/files/app.js
__dirname /data/data/com.openmoney.p2p/files
process.userPath /data/data/com.openmoney.p2p/files/
```

**Comment by obastemur** [comment]
Latest commit should fix them all. PS: .so / .java / .js files are updated.

**Comment by deefactorial** [comment]
The reason the static file express server example is not working for this issue is because the fs.stat function isn't implemented yet, is that an issue with the binaries ?

```
E/jxcore-log﹕ etag@/data/data/com.openmoney.p2p/files/jxcore/node_modules/express/node_modules/etag/index.js:55:1
    setHeader@/data/data/com.openmoney.p2p/files/jxcore/node_modules/express/node_modules/send/index.js:739:15
    SendStream.prototype.send@/data/data/com.openmoney.p2p/files/jxcore/node_modules/express/node_modules/send/index.js:507:3
    sendIndex/next/<@/data/data/com.openmoney.p2p/files/jxcore/node_modules/express/node_modules/send/index.js:645:7
    makeCallback/<@fs.js:84:12
    fs.stat@fs.js:780:7
    next@/data/data/com.openmoney.p2p/files/jxcore/node_modules/express/node_modules/send/index.js:641:5
    sendIndex@/data/data/com.openmoney.p2p/files/jxcore/node_modules/express/node_modules/send/index.js:649:3
    SendStream.prototype.pipe@/data/data/com.openmoney.p2p/files/jxcore/node_modules/express/node_modules/send/index.js:475:5
    serveStatic@/data/data/com.openmoney.p2p/files/jxcore/node_modules/express/node_modules/serve-static/index.js:111:5
    handle@/data/data/com.openmoney.p2p/files/jxcore/node_modules/express/lib/router/layer.js
```

I've made a github repo of a work around that excludes the etag that works
the repo is available here:
[jxcore-cordova-tests](https://github.com/deefactorial/jxcore-cordova-tests.git)

**Comment by ktrzeciaknubisa** [comment]
We know, that SM still has problem with [typeof stat](https://github.com/jxcore/jxcore/issues/242#issuecomment-92894876) for packaged assets and I guess that's the exact problem, right? Etag's check `var isStats = isstats(entity)` in _express/node_modules/etag/index.js:44_ fails because of that.

**Comment by obastemur** [comment]
`We know, that SM still has problem with typeof stat for packaged assets`

This is not SM's problem. Etag's check was buggy and the author has fixed it. Probably it's not updated on express yet. However we can manage it for JXStats object.

**Comment by ktrzeciaknubisa** [comment]
> However we can manage it for JXStats object. 

I made an attempt once and it worked for `typeof stat === "object"`, but then `stat instanceof fs.Stats` wasn't `true` anymore, so let's keep in mind that too.

**Comment by deefactorial** [comment]
I have updated my repo [jxcore-cordova-tests](https://github.com/deefactorial/jxcore-cordova-tests.git) to test this issue with the latest changes. The issue still persists at this time.

**Comment by obastemur** [comment]
https://github.com/jxcore/jxcore-cordova/commit/ed283ddf8b32459b17fd6540fe7e800648b1e51f fixes res.sendFile Android problem. Tested with @deefactorial's test project. Thanks for all the input.

**Comment by dougwilson** [comment]
Express 4.12.4 includes the updated `etag` module now.

**Comment by obastemur** [comment]
@dougwilson Thanks!
