### ISSUE TITLE
jxcore express sample failed to run on Xiaomi Box

### ISSUE THREAD

**Issue by jyang** [jxcore/jxcore-cordova#55]
jxcore express sample runs well on all my devices except a Xiaomi Box similar to or older than this one:

http://www.amazon.com/Xiaomi-1-5ghz-Internet-Android-Bluetooth/dp/B00JIVZ6MY/ref=sr_1_5?ie=UTF8&qid=1438029545&sr=8-5&keywords=xiaomi+box

The app launches with a blank screen and then it quits without any error I can find. OS is Android 4.x (not sure exactly which) without Google Play Services. Any clue? Any dependency potentially missing?

**Comment by obastemur** [comment]
Are you able to read logcat?

**Comment by jyang** [comment]
It's very hard to do anything on this box. So I tried a different old device based on the same Android version 4.0.4. Here is the relevant part of the log. targetSdkVersion is 15 (4.0.3). Is 4.0.4 too old to be supported?

...
07-30 22:13:51.690 I/TwDVFSBroadcastReceiver(466): onLauncherIntent
07-30 22:13:51.690 D/PowerManager(466): DVFSLock :  acquire : timeout : 1000
07-30 22:13:51.690 I/power   (197): **\* acquire_dvfs_lock : lockType : 1  freq : 1000000 
07-30 22:13:51.690 D/PowerManagerService(197): acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1000000  uid : 1000  pid : 466  tag : TwDVFSBroadcastReceiver
07-30 22:13:51.780 I/InputReader(197): Touch event's action is 0x1 (deviceType=0) [pCnt=1, pending(waiting finished signal)=0, s=]
07-30 22:13:51.780 I/InputDispatcher(197): Delivering touch to current input target: action: 0x1
07-30 22:13:51.780 I/InputDispatcher(197): Delivering touch to current input target: action: 0x1
07-30 22:13:51.780 I/InputDispatcher(197): Delivering touch to current input target: action: 0x1
07-30 22:13:51.780 I/ActivityManager(197): START {intent.toShortString} from pid 494
07-30 22:13:51.780 D/PowerManagerService(197): acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1000000  uid : 1000  pid : 197  tag : ActivityManager
07-30 22:13:51.780 W/ActivityManager(197): mDVFSLock.acquire()
07-30 22:13:51.790 D/Launcher.HomeFragment(494): onPause
07-30 22:13:51.790 D/Launcher(494): onPause
07-30 22:13:51.790 D/ProgramMonitor(8078): START onReceive()_intent : Intent { act=com.sec.android.intent.action.HOME_PAUSE flg=0x10 cmp=xxxx }
07-30 22:13:51.810 D/dalvikvm(9456): Late-enabling CheckJNI
07-30 22:13:51.830 D/OpenGLRenderer(494): Flushing caches (mode 1)
07-30 22:13:51.830 I/ActivityManager(197): Start proc app.processName for activity hostingNameStr: pid=9456 uid=10086 gids={3003}
07-30 22:13:51.840 D/Launcher(494): onTrimMemory. Level: 20
07-30 22:13:51.840 D/DEFERED_APP_VISIBILITY(197): tweaking closing app
07-30 22:13:51.860 D/OpenGLRenderer(494): Flushing caches (mode 0)
07-30 22:13:51.890 I/dalvikvm(9456): Could not find method android.app.Activity.startActivityForResult, referenced from method org.apache.cordova.CordovaActivity.startActivityForResult
07-30 22:13:51.890 W/dalvikvm(9456): VFY: unable to resolve virtual method 23: Landroid/app/Activity;.startActivityForResult (Landroid/content/Intent;ILandroid/os/Bundle;)V
07-30 22:13:51.890 D/dalvikvm(9456): VFY: replacing opcode 0x6f at 0x0005
07-30 22:13:51.900 I/dalvikvm(9456): Could not find method android.webkit.WebView.setWebContentsDebuggingEnabled, referenced from method org.apache.cordova.engine.SystemWebViewEngine.enableRemoteDebugging
07-30 22:13:51.900 W/dalvikvm(9456): VFY: unable to resolve static method 207: Landroid/webkit/WebView;.setWebContentsDebuggingEnabled (Z)V
07-30 22:13:51.900 D/dalvikvm(9456): VFY: replacing opcode 0x71 at 0x0001
07-30 22:13:51.900 I/dalvikvm(9456): Could not find method android.webkit.WebSettings.setMediaPlaybackRequiresUserGesture, referenced from method org.apache.cordova.engine.SystemWebViewEngine.initWebViewSettings
07-30 22:13:51.900 W/dalvikvm(9456): VFY: unable to resolve virtual method 196: Landroid/webkit/WebSettings;.setMediaPlaybackRequiresUserGesture (Z)V
07-30 22:13:51.900 D/dalvikvm(9456): VFY: replacing opcode 0x6e at 0x007a
07-30 22:13:51.930 I/webclipboard(9456): clipservice: android.sec.clipboard.ClipboardExManager@413c1fa8
07-30 22:13:51.960 I/dalvikvm(9456): Could not find method android.webkit.CookieManager.setAcceptThirdPartyCookies, referenced from method org.apache.cordova.engine.SystemCookieManager.<init>
07-30 22:13:51.960 W/dalvikvm(9456): VFY: unable to resolve virtual method 162: Landroid/webkit/CookieManager;.setAcceptThirdPartyCookies (Landroid/webkit/WebView;Z)V
07-30 22:13:51.960 D/dalvikvm(9456): VFY: replacing opcode 0x6e at 0x0016
07-30 22:13:51.960 I/dalvikvm(9456): Could not find method android.webkit.CookieManager.flush, referenced from method org.apache.cordova.engine.SystemCookieManager.flush
07-30 22:13:51.960 W/dalvikvm(9456): VFY: unable to resolve virtual method 157: Landroid/webkit/CookieManager;.flush ()V
07-30 22:13:51.960 D/dalvikvm(9456): VFY: replacing opcode 0x6e at 0x0008
07-30 22:13:51.970 W/dalvikvm(9456): VFY: unable to find class referenced in signature (Landroid/webkit/ClientCertRequest;)
07-30 22:13:51.980 W/dalvikvm(9456): VFY: unable to find class referenced in signature (Landroid/webkit/ClientCertRequest;)
07-30 22:13:51.980 I/dalvikvm(9456): Could not find method android.webkit.WebViewClient.onReceivedClientCertRequest, referenced from method org.apache.cordova.engine.SystemWebViewClient.onReceivedClientCertRequest
07-30 22:13:51.980 W/dalvikvm(9456): VFY: unable to resolve virtual method 212: Landroid/webkit/WebViewClient;.onReceivedClientCertRequest (Landroid/webkit/WebView;Landroid/webkit/ClientCertRequest;)V
07-30 22:13:51.980 D/dalvikvm(9456): VFY: replacing opcode 0x6f at 0x001a
07-30 22:13:51.980 I/dalvikvm(9456): Could not find method android.webkit.WebChromeClient$FileChooserParams.createIntent, referenced from method org.apache.cordova.engine.SystemWebChromeClient.onShowFileChooser
07-30 22:13:51.980 W/dalvikvm(9456): VFY: unable to resolve virtual method 176: Landroid/webkit/WebChromeClient$FileChooserParams;.createIntent ()Landroid/content/Intent;
07-30 22:13:51.980 D/dalvikvm(9456): VFY: replacing opcode 0x6e at 0x0000
07-30 22:13:51.990 D/SystemWebViewEngine(9456): CordovaWebView is running on device made by: samsung
07-30 22:13:51.990 I/SystemWebViewEngine(9456): Disabled addJavascriptInterface() bridge since Android version is old.
07-30 22:13:52.020 D/WML_SISO(9456): InitPasteboardJni
07-30 22:13:52.080 D/libEGL  (9456): loaded /system/lib/egl/libEGL_tegra.so
07-30 22:13:52.080 D/libEGL  (9456): loaded /system/lib/egl/libGLESv1_CM_tegra.so
07-30 22:13:52.120 D/libEGL  (9456): loaded /system/lib/egl/libGLESv2_tegra.so
07-30 22:13:52.160 D/OpenGLRenderer(9456): Enabling debug mode 0
07-30 22:13:52.170 I/ClipboardServiceEx(197): Send intent for dismiss clipboard dialog inside hideCurrentInputLocked() !
07-30 22:13:52.180 W/InputManagerService(197): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@42494768 (uid=10171 pid=494)
07-30 22:13:52.190 V/InputManagerService(197): Starting input on non-focused client mCurClient info is ClientState{42669b88 uid 10086 pid 9456}
07-30 22:13:52.200 I/ActivityManager(197): Displayed shortComponentName: +404ms
07-30 22:13:52.200 D/CLIPBOARD(9456): Hide Clipboard dialog at Starting input: finished by someone else... !
07-30 22:13:52.440 D/Launcher.HomeFragment(494): onStop
07-30 22:13:52.440 D/Launcher.Workspace(494): onStop
07-30 22:13:52.440 D/Launcher(494): onStop
07-30 22:13:52.440 W/ActivityManager(197): mDVFSLock.release()
07-30 22:13:52.690 I/power   (197): **\* release_dvfs_lock : lockType : 1 
07-30 22:13:52.690 D/PowerManagerService(197): releaseDVFSLockLocked : all DVFS_MIN_LIMIT are released 
07-30 22:13:53.190 W/PowerManagerService(197): Timer 0x7->0x3|0x0
07-30 22:13:53.190 I/PowerManagerService(197): Ulight 7->3|0
07-30 22:13:53.190 D/PowerManagerService(197): setLightBrightness : mButtonLight : 0
07-30 22:13:53.390 D/JsMessageQueue(9456): Set native->JS mode to OnlineEventsBridgeMode
07-30 22:13:53.390 D/chromium(9456): Unknown chromium error: -6
07-30 22:13:53.720 I/GATE    (9456): <GATE-M>DEV_ACTION_COMPLETED</GATE-M>
07-30 22:13:53.740 I/ClipboardServiceEx(197): Send intent for dismiss clipboard dialog inside hideCurrentInputLocked() !
07-30 22:13:53.830 D/dalvikvm(9456): Trying to load lib /data/data/com.example.workshop/lib/libjxcore.so 0x4136ce50
07-30 22:13:53.850 D/dalvikvm(9456): Added shared lib /data/data/com.example.workshop/lib/libjxcore.so 0x4136ce50
07-30 22:13:53.850 D/jxcore_app_log(9456): JniHelper::setJavaVM(0xccf540), pthread_self() = 1074996456
07-30 22:13:53.850 D/JX-Cordova(9456): jxcore cordova android initializing
07-30 22:13:53.950 D/dalvikvm(9456): GC_CONCURRENT freed 741K, 13% free 7295K/8327K, paused 2ms+2ms
07-30 22:13:54.000 W/jxcore-log(9456): Initializing JXcore engine
07-30 22:13:54.000 W/jxcore-log(9456): JXcore engine is ready
07-30 22:13:54.020 W/jxcore-log(9456): Starting JXcore engine
07-30 22:13:54.100 F/libc    (9456): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1)
07-30 22:13:54.510 I/DEBUG   (8530): **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
07-30 22:13:54.510 I/DEBUG   (8530): Build fingerprint: 'samsung/GT-P7510/GT-P7510:4.0.4/IMM76D/UELPL:user/release-keys'
07-30 22:13:54.510 I/DEBUG   (8530): pid: 9456, tid: 9456  >>> com.example.workshop <<<
07-30 22:13:54.510 I/DEBUG   (8530): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadbaad
07-30 22:13:54.510 I/DEBUG   (8530):  r0 deadbaad  r1 00000001  r2 40000000  r3 00000000
07-30 22:13:54.510 I/DEBUG   (8530):  r4 00000000  r5 00000027  r6 bef18540  r7 0000000a
07-30 22:13:54.510 I/DEBUG   (8530):  r8 00000002  r9 00fe5b48  10 bef18608  fp bef1853c
07-30 22:13:54.510 I/DEBUG   (8530):  ip ffffffff  sp bef18508  lr 400fd679  pc 400f9a2c  cpsr 60000030
07-30 22:13:54.510 I/DEBUG   (8530):  d0  400000003eaaaaab  d1  44a0200000000501
07-30 22:13:54.510 I/DEBUG   (8530):  d2  bf800000ffffffff  d3  44a02000bf800000
07-30 22:13:54.510 I/DEBUG   (8530):  d4  bf800000bf800000  d5  44a04000bf800000
07-30 22:13:54.510 I/DEBUG   (8530):  d6  01162c8000000000  d7  417162c808000000
07-30 22:13:54.510 I/DEBUG   (8530):  d8  0000000000000000  d9  0000000000000000
07-30 22:13:54.510 I/DEBUG   (8530):  d10 0000000000000000  d11 0000000000000000
07-30 22:13:54.510 I/DEBUG   (8530):  d12 0000000000000000  d13 0000000000000000
07-30 22:13:54.510 I/DEBUG   (8530):  d14 0000000000000000  d15 0000000000000000
07-30 22:13:54.510 I/DEBUG   (8530):  scr 80000010
07-30 22:13:54.510 I/DEBUG   (8530): 
07-30 22:13:54.680 I/DEBUG   (8530):          #00  pc 00017a2c  /system/lib/libc.so
07-30 22:13:54.680 I/DEBUG   (8530):          #01  lr 400fd679  /system/lib/libc.so
07-30 22:13:54.680 I/DEBUG   (8530): 
07-30 22:13:54.680 I/DEBUG   (8530): code around pc:
07-30 22:13:54.680 I/DEBUG   (8530): 400f9a0c 4623b15c 2c006824 e026d1fb b12368db  .#F$h.,..&..h#.
07-30 22:13:54.680 I/DEBUG   (8530): 400f9a1c 21014a17 6011447a 48124798 24002527  .J.!zD.`.G.H'%.$
07-30 22:13:54.680 I/DEBUG   (8530): 400f9a2c f7f47005 2106ee02 ee9ef7f5 460aa901  .p.....!.......F
07-30 22:13:54.680 I/DEBUG   (8530): 400f9a3c f04f2006 94015380 94029303 ea5af7f5  . O..S........Z.
07-30 22:13:54.680 I/DEBUG   (8530): 400f9a4c 4622a905 f7f52002 f7f4ea64 2106edee  .."F. ..d......!
07-30 22:13:54.680 I/DEBUG   (8530): 
07-30 22:13:54.680 I/DEBUG   (8530): code around lr:
07-30 22:13:54.680 I/DEBUG   (8530): 400fd658 41f0e92d 46804c0c 447c2600 68a56824  -..A.L.F.&|D$h.h
07-30 22:13:54.680 I/DEBUG   (8530): 400fd668 e0076867 300cf9b5 dd022b00 47c04628  gh.....0.+..(F.G
07-30 22:13:54.680 I/DEBUG   (8530): 400fd678 35544306 37fff117 6824d5f4 d1ee2c00  .CT5...7..$h.,..
07-30 22:13:54.680 I/DEBUG   (8530): 400fd688 e8bd4630 bf0081f0 00028e86 41f0e92d  0F..........-..A
07-30 22:13:54.680 I/DEBUG   (8530): 400fd698 fb01b086 9004f602 461f4815 4615460c  .........H.F.F.F
07-30 22:13:54.680 I/DEBUG   (8530): 
07-30 22:13:54.680 I/DEBUG   (8530): memory map around addr deadbaad:
07-30 22:13:54.680 I/DEBUG   (8530): beef8000-bef19000 [stack]
07-30 22:13:54.680 I/DEBUG   (8530): (no map for address)
07-30 22:13:54.680 I/DEBUG   (8530): ffff0000-ffff1000 [vectors]
07-30 22:13:54.680 I/DEBUG   (8530): 
07-30 22:13:54.680 I/DEBUG   (8530): stack:
07-30 22:13:54.680 I/DEBUG   (8530):     bef184c8  bef1859c  [stack]
07-30 22:13:54.680 I/DEBUG   (8530):     bef184cc  5f669b68  /data/data/com.example.workshop/lib/libjxcore.so
07-30 22:13:54.680 I/DEBUG   (8530):     bef184d0  0001e237  
07-30 22:13:54.680 I/DEBUG   (8530):     bef184d4  bef184f8  [stack]
07-30 22:13:54.680 I/DEBUG   (8530):     bef184d8  40126774  /system/lib/libc.so
07-30 22:13:54.680 I/DEBUG   (8530):     bef184dc  4012b8c0  
07-30 22:13:54.680 I/DEBUG   (8530):     bef184e0  00000000  
07-30 22:13:54.680 I/DEBUG   (8530):     bef184e4  400fd679  /system/lib/libc.so
07-30 22:13:54.680 I/DEBUG   (8530):     bef184e8  00000000  
07-30 22:13:54.680 I/DEBUG   (8530):     bef184ec  bef1851c  [stack]
07-30 22:13:54.680 I/DEBUG   (8530):     bef184f0  bef18540  [stack]
07-30 22:13:54.680 I/DEBUG   (8530):     bef184f4  0000000a  
07-30 22:13:54.680 I/DEBUG   (8530):     bef184f8  00000002  
07-30 22:13:54.680 I/DEBUG   (8530):     bef184fc  400fc7e5  /system/lib/libc.so
07-30 22:13:54.680 I/DEBUG   (8530):     bef18500  e3a070ad  
07-30 22:13:54.680 I/DEBUG   (8530):     bef18504  ef9000ad  
07-30 22:13:54.680 I/DEBUG   (8530): #00 bef18508  00000002  
07-30 22:13:54.680 I/DEBUG   (8530):     bef1850c  bef18534  [stack]
07-30 22:13:54.680 I/DEBUG   (8530):     bef18510  5fb2f520  
07-30 22:13:54.680 I/DEBUG   (8530):     bef18514  5f2c1544  /data/data/com.example.workshop/lib/libjxcore.so
07-30 22:13:54.680 I/DEBUG   (8530):     bef18518  5f73f26c  /data/data/com.example.workshop/lib/libjxcore.so
07-30 22:13:54.680 I/DEBUG   (8530):     bef1851c  fffffbdf  
07-30 22:13:54.680 I/DEBUG   (8530):     bef18520  bef18540  [stack]
07-30 22:13:54.680 I/DEBUG   (8530):     bef18524  5f73f26c  /data/data/com.example.workshop/lib/libjxcore.so
07-30 22:13:54.680 I/DEBUG   (8530):     bef18528  010ea930  [heap]
07-30 22:13:54.680 I/DEBUG   (8530):     bef1852c  5f2b8248  /data/data/com.example.workshop/lib/libjxcore.so
07-30 22:13:54.680 I/DEBUG   (8530):     bef18530  5f903d58  /data/data/com.example.workshop/lib/libjxcore.so
07-30 22:13:54.680 I/DEBUG   (8530):     bef18534  ffffffff  
07-30 22:13:54.680 I/DEBUG   (8530):     bef18538  bef185ac  [stack]
07-30 22:13:54.680 I/DEBUG   (8530):     bef1853c  5f2b8f20  /data/data/com.example.workshop/lib/libjxcore.so
07-30 22:13:54.680 I/DEBUG   (8530):     bef18540  4012b50c  
07-30 22:13:54.680 I/DEBUG   (8530):     bef18544  4012b50c  
07-30 22:13:54.680 I/DEBUG   (8530):     bef18548  011c1930  [heap]
07-30 22:13:54.680 I/DEBUG   (8530):     bef1854c  011c1938  [heap]
...

**Comment by obastemur** [comment]
Thanks for the details. I will try to reproduce

**Comment by obastemur** [comment]
@jyang couldn't reproduce the problem on a device with similar samsung signature. Are you able to adb shell to this device and run jxcore as a standalone binary? (http://jxcore.com/downloads/)

**Comment by jyang** [comment]
Thanks for looking into it! What's the Android version on your device? I think that is significant. I ran the sample successfully on another old device with Android 4.2.2.

**Comment by obastemur** [comment]
Okay, I was able to reproduce this on Alcatel one touch tablet with Android 4.0.4 . Interestingly it works for 4.0.1 or 2.3.7. Trying to figure out what is different or special with 4.0.4.

**Comment by obastemur** [comment]
https://github.com/jxcore/jxcore/pull/501 fixes this issue. I've just tested on 4.0.3 and it worked. If you can compile the binaries from the sources and test, it could be nice though. Otherwise please wait for the release.

**Comment by jyang** [comment]
Thank you so much, obastemur! Will wait for the release.

**Comment by obastemur** [comment]
It's released. See `https://github.com/jxcore/jxcore-cordova-release`

**Comment by jyang** [comment]
Thanks! Will try it out.

**Comment by jyang** [comment]
Fix confirmed on Mi Box running Android 4.0.4. Thanks!
