### ISSUE TITLE
Are native extensions working? (using sample code)

### ISSUE THREAD

**Issue by julianh2o** [jxcore/jxcore-cordova#56]
How is the JXcoreExtension.\* files loaded?

I'm trying to get the basic native calls in the sample/www example working but haven't had any luck so far.

I'm seeing a message in the log that suggests that the JXCoreExtension file is not being picked up under iOS:
Jul 31 00:24:37 [...][98019]: Native method ScreenInfo not found.
Jul 31 00:15:35 [...][93265]: Native method ScreenBrightness not found.

What is the right method for getting this extension file loaded and calling it correctly?

**Comment by obastemur** [comment]
Update plugin.xml to copy also JXcoreExtension.m and thats it

**Comment by julianh2o** [comment]
Thanks, I managed to get this to work!

I've written a build script that will automatically copy updates to these files from my source directories into the plugins directory, but in general I think I'd prefer seeing a better way to pick up those plugins. I'm not sure if that's possible, but it'd be great to be able to create an optional JXcoreExtension.\* somewhere specific in your source tree and have it automatically picked up by the plugin during compilation.
