### ISSUE TITLE
fs.fileReadSync issues with pidlockfile.check

### ISSUE THREAD

**Issue by PaulosV** [jxcore/jxcore-cordova#61]
I have tried (for educational and research purposes) to run Zetta on JXcore, and after that on JXcore-Cordova on Android. While it works just fine on JXcore for desktop, I have this issue running it on JXcore-Cordova.

The main issue is that readFile function returns this nasty exception:

```
08-12 14:13:27.142  22127-22127/com.example.hello E/jxcore﹕ Error!: /data/data/com.example.hello/cache/.devices/medea.lock does not exist
```

stack attached @ http://pastebin.com/3BfVzL4A

Generally, I tracked the problem down to `jxcore_cordova.js`, to the `readfilesync` extension function. It is invoked by `pidlockfile.check` function. `readfilesync` behaves differently from the JXcore's usual behavior; does not provide either errorcode or any more information when the file is missing, and it kinda runs away from any exception catching mechanism; I only caught it via `onUnhandledException`.

Test case: install zetta, strip any .gz files and then to `app.js`:

```
var zetta = require('zetta');
zetta().name('hi').listen(23456);
```

Since then, I've tried a couple of workarounds for this issue, setting error's code to ENOENT, and also removing the extension altogether, but as we also need to access the app's assets in the phone, it's not that easy. I have also tried different paths, so that I could rule out permission issues.

**Comment by ktrzeciaknubisa** [comment]
I'm shooting in the dark, but looking at the stack I noticed, that third call from top fails at async `fs.readFile()`. However I cannot say yet if that explains anything. I'll take a look at it.

**Comment by PaulosV** [comment]
Simplified version that I tried that only requires `pidlockfile`:

```
var pidlock = require('pidlockfile');
var mypath = '/storage/sdcard1/zettor/';

pidlock.check(mypath + 'hi.lock', function(err, data) {
if(err) {
    console.log("i'm screwed", err);
    pidlock.lock(mypath + 'hi.lock', function(err2, data2) {
    if(err2) {
        console.log("noooo", err2);
    } else {
        console.log("YEESSSS");
    }
});
} else {
console.log("it works");
}});
```

throws exception at pidlock.check without going to the anonymous function. JXcore on desktop processes this just fine.

**Comment by ktrzeciaknubisa** [comment]
OK, this commit aafac4b54ba34ca2c78cc55b1f7b36eca92ac5df restores consistent behavior. Now you can get the error with `pidlock.check()` which calls `fs.readFile()` which in turn calls `readfilesync()` which was throwing an exception.

However on my desktop I get "YEESSSS" while on android "noooo". Somehow `pidlock.lock()` did not succeed. But I didn't go to find out why.

**Comment by PaulosV** [comment]
Maybe permission issues, that can happen relatively easily. Thank you nevertheless, I'll test it ASAP and eventually close :+1:

**Comment by PaulosV** [comment]
It works! thank you :) closing
