### ISSUE TITLE
Detecting if we are on Android, iOS or Desktop

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore-cordova#63]
For testing purposes it would be really nice if there was an interface we could call that could tell us if we are on Android, iOS or a desktop OS.

Right now we are hacking up something involving detecting if the Mobile object is defined but this is really futzy. It would be nice to have a Client object (I keep saying, Mobile is a bad name) and we could do Client.deviceType and get back an object that returned things like Hardware, OS, Version, etc.

**Comment by ktrzeciaknubisa** [comment]
Hi, you may use `process.platform` which is "android" or "ios" on mobiles. Also [jxcore.utils.OSInfo()](https://github.com/jxcore/jxcore/blob/master/doc/api/jxcore-utils.markdown#osinfo) returns some useful data.

**Comment by obastemur** [comment]
Besides `http://jxcore.com/docs/jxcore-utils.html#osinfo`
P.S. @ktrzeciaknubisa docs needs an update

**Comment by ktrzeciaknubisa** [comment]
Indeed. Updated.

**Comment by yaronyg** [comment]
Awesome! Thanks!
