### ISSUE TITLE
fs.readFile failed on Android

### ISSUE THREAD

**Issue by AlexZhouAA** [jxcore/jxcore-cordova#73]
I tried to run code below

<pre><code>
  fs.readFile(path.join(__dirname, "public/img//products/example.jpg"), function(err, data){
    if(err) ...
    else ....
  });
</code></pre>

I got error below
 <pre><code>
@/data/data/com.does_inc.salesplus/files/www/jxcore/app.js:122:2   handle@/data/data/com.does_inc.salesplus/files/www/jxcore/node_modules/express/lib/router/layer.js:95:5
next@/data/data/com.does_inc.salesplus/files/www/jxcore/node_modules/express/lib/router/route.js:131:7
dispatch@/data/data/com.does_inc.salesplus/files/www/jxcore/node_modules/express/lib/router/route.js:112:3
handle@/data/data/com.does_inc.salesplus/files/www/jxcore/node_modules/express/lib/router/layer.js:95:5
next/<@/data/data/com.does_inc.salesplus/files/www/jxcore/node_modules/express/lib/router/index.js:277:1
process_params@/data/data/com.does_inc.salesplus/files/www/jxcore/node_modules/express/lib/router/index.js:330:1
next@/data/data/com.does_inc.salesplus/files/www/jxcore/node_modules/express/lib/router/index.js:271:5
error@/data/data/com.does_inc.salesplus/files/www/jxcore/node_modules/express/node_modules/serve-static/index.js:120:7
emit@events.js:82:7
error@/data/data/com.does_inc.salesplus/files/www/jxcore/node_modules/express/node_modules/send/index.js:245:1
onStatError@/data/data/com.does_inc.salesplus/files/www/jxcore/node_modules/express/node_modules/send/index.js:356:7
next@/data/data/com.does_inc.salesplus/files/www/jxcore/node_modules/express/node_modules/send/index.js:630:11
onstat@/data/data/com.does_inc.salesplus/files/www/jxcore/node_modules/express/node_modules/send/index.js:619:1
makeCallback/<@fs.js:84:12
</code></pre>

Please Help

**Comment by ktrzeciaknubisa** [comment]
Hi, except for the stack trace, do you have any error message?

Also (although this shouldn't matter) please check without double slash in "public/img//products/example.jpg"

And obviously the image file is inside an app package, right?

**Comment by AlexZhouAA** [comment]
I'm sorry I made a paste mistake, there's no double slash in the running code.

Yes, the file is inside the app package

**Comment by ktrzeciaknubisa** [comment]
> except for the stack trace, do you have any error message?

**Comment by AlexZhouAA** [comment]
No more error message.

**Comment by ktrzeciaknubisa** [comment]
Without an error message I can only guess, that the file was not found. Could you please try to apply manually the fix from https://github.com/jxcore/jxcore-cordova/commit/aafac4b54ba34ca2c78cc55b1f7b36eca92ac5df and see if that helps?

**Comment by AlexZhouAA** [comment]
OK, thanks, I'll try that

**Comment by AlexZhouAA** [comment]
Great, It works. Thanks a lot.

By the way, does fs.writeFile within folder (__dirname + "public/" ) work or not?

**Comment by ktrzeciaknubisa** [comment]
I'm not sure, if the permissions would allow this - never tried this myself. Regardless, please keep in mind, that your `./public` folder (or any other folder of your app for that matter), is part of virtual directory structure of the app package (does not reside directly in android's filesystem), thus if you would try to save any file, you would need to create a real `./public` folder in real filesystem and write there.

**Comment by AlexZhouAA** [comment]
I tried and failed,
I got error message like
<code>
r{"message":"ENOENT, open '/data/data/com.does_inc.salesplus/files/www/jxcore/public/encodeTable.html'","errno":34,"code":"ENOENT","path":"/data/data/com.does_inc.salesplus/files/www/jxcore/public/encodeTable.html"}
</code>

Thanks again

**Comment by obastemur** [comment]
See https://github.com/jxcore/jxcore-cordova#where-to-save-your-files-write-access-on-mobile-targets-erofs-error- for saving files (cross platform) on mobile devices.

**Comment by AlexZhouAA** [comment]
Excellent, have a nice day
