### ISSUE TITLE
Unable to build in xCode

### ISSUE THREAD

**Issue by itsallrelative** [jxcore/jxcore-cordova#74]
Just updated to xCode 7, and am now not able to build my cordova / ionic project. The main error I am seeing is: 

ld: in /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja Scan/Plugins/io.jxcore.node/libcares.a(ares_strcasecmp.o), building for iOS simulator, but linking in object file built for OSX, for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation).

and here is the entire build log:

Ld /Users/tfree2/Library/Developer/Xcode/DerivedData/Ninja_Scan-agrdvbengrwwmebkluhamofsddea/Build/Products/Debug-iphonesimulator/Ninja\ Scan.app/Ninja\ Scan normal x86_64
    cd /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -L/Users/tfree2/Library/Developer/Xcode/DerivedData/Ninja_Scan-agrdvbengrwwmebkluhamofsddea/Build/Products/Debug-iphonesimulator -L/Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja\ Scan/Plugins/com.paypal.cordova.mobilesdk -L/Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja\ Scan/Plugins/io.jxcore.node -F/Users/tfree2/Library/Developer/Xcode/DerivedData/Ninja_Scan-agrdvbengrwwmebkluhamofsddea/Build/Products/Debug-iphonesimulator -filelist /Users/tfree2/Library/Developer/Xcode/DerivedData/Ninja_Scan-agrdvbengrwwmebkluhamofsddea/Build/Intermediates/Ninja\ Scan.build/Debug-iphonesimulator/Ninja\ Scan.build/Objects-normal/x86_64/Ninja\ Scan.LinkFileList -mios-simulator-version-min=6.0 -Xlinker -objc_abi_version -Xlinker 2 -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -fobjc-arc -fobjc-link-runtime -framework AssetsLibrary /Users/tfree2/Library/Developer/Xcode/DerivedData/Ninja_Scan-agrdvbengrwwmebkluhamofsddea/Build/Products/Debug-iphonesimulator/libCordova.a -framework CoreGraphics -framework MobileCoreServices -lPayPalMobile -framework Accelerate -framework AudioToolbox -framework AVFoundation -framework CFNetwork -weak_framework CoreLocation -weak_framework CoreMedia -framework CoreVideo -framework MessageUI -framework OpenGLES -framework Security -framework SafariServices -framework SystemConfiguration -framework QuartzCore -framework UIKit -lc++ -lPayPalMobile -liconv -framework CoreImage -lcares -lchrome_zlib -lhttp_parser -ljx -lmozjs -lopenssl -lsqlite3 -luv -lleveldb -lleveldown -lsnappy -lstdc++.6.0.9 -framework Foundation -Xlinker -dependency_info -Xlinker /Users/tfree2/Library/Developer/Xcode/DerivedData/Ninja_Scan-agrdvbengrwwmebkluhamofsddea/Build/Intermediates/Ninja\ Scan.build/Debug-iphonesimulator/Ninja\ Scan.build/Objects-normal/x86_64/Ninja\ Scan_dependency_info.dat -o /Users/tfree2/Library/Developer/Xcode/DerivedData/Ninja_Scan-agrdvbengrwwmebkluhamofsddea/Build/Products/Debug-iphonesimulator/Ninja\ Scan.app/Ninja\ Scan

ld: in /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja Scan/Plugins/io.jxcore.node/libcares.a(ares_strcasecmp.o), building for iOS simulator, but linking in object file built for OSX, for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by itsallrelative** [comment]
Figured it out. It was actually an error with xcode 7 enabling bitcode on build options by default. This can be disabled in the build settings.

**Comment by ktrzeciaknubisa** [comment]
Thanks for an update. Might be useful for others :)

**Comment by obastemur** [comment]
I'm working on embedding bitcode. Lets keep this issue open until it's properly fixed.

**Comment by ktrzeciaknubisa** [comment]
After all I'm not sure, that this is just about disabling Bitcode for xCode 7. I did that, but it didn't help. Still I'm not able to build the app from xCode gui not to mention that from command line obviously it fails too:

``` bash
$ cordova run
```

For the moment I think I'm going to downgrade xCode.

**Comment by ktrzeciaknubisa** [comment]
**Update**: ok, until now I was trying to launch an app on iOS simulator, and so disabling Bitcode did not help, as I mentioned before.

But then I looked closely at error message:

> building for iOS simulator, but linking in object file built for OSX, for architecture x86_64

so I plugged my iPhone 4 device, and tried again from console:

``` bash
$ cordova run ios --device
```

to see a different error message:

> ios/HelloWorld/Plugins/io.jxcore.node/libjx.a(jx_result.o)' does not contain bitcode. 
> You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

And that is strange, because they want me to **enable** Bitcode. Next I opened the project in xCode 7, and the Bitcode was already enabled, but the app would not build. Only by **disabling** Bitcode (as @tomandhisjones adviced) I was finally able to run the app on the device. (simulators still don't work).

**Comment by ktrzeciaknubisa** [comment]
I wrote a plugin's hook, which fires on `after_platform_add` and adds `ENABLE_BITCODE = NO;` to _project.pbxproj_ and allows to run jxcore-cordova on the device without launching xCode 7. 

1) add this to `io.jxcore.node/plugin.xml` (inside `<platform name="ios">` tag):

``` xml
<hook type="after_platform_add" src="scripts/disable_bitcode.js" />
```

2) write the following code into the file _io.jxcore.node/scripts/disable_bitcode.js_ :

``` js
var fs = require('fs');
var path = require('path');

// rootdir points to "platforms"
var rootdir = process.argv[2];
if (!rootdir)
  process.exit();


function getProjectName() {
  var cfgPath = path.join(rootdir, "..", 'config.xml');

  var xml = fs.readFileSync(cfgPath, 'utf-8');
  var r = /<name>([\s\S]*)<\/name>/mi.exec(xml);

  return r[1].trim();
}

var pbxprojPath = path.join(rootdir, 'ios', getProjectName() + ".xcodeproj" , 'project.pbxproj');

var pbxproj = fs.readFileSync(pbxprojPath, 'utf8');

if (pbxproj.indexOf("ENABLE_BITCODE") === -1) {
  var src = 'buildSettings = {';
  var dst = src + "\nENABLE_BITCODE = NO;\n";
  var result = pbxproj.replace(new RegExp(src, "g"), dst);
  fs.writeFileSync(pbxprojPath, result, 'utf8');
}
```

3) it will fire on:

``` bash
$ cordova platform add ios
```

@obastemur Let me know if we want to add it into the repo.

**Comment by obastemur** [comment]
Latest 0.0.5 on `jxcore-cordova-release` fixes the issue. No longer manual switch etc. is needed.
