### ISSUE TITLE
Should JXcore v0.3.0.7 be in jxcore-cordova 0.0.7?

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore-cordova#82]
I just ran into the nock error (the undefined info object) that I know was fixed in v0.3.0.7 using jxcore-cordova 0.0.7. So does this mean that jxcore-cordova 0.0.7 isn't using JXcore v0.3.0.7?

**Comment by obastemur** [comment]
No it's not. The plan was to release `0.1` with the upcoming `0.3.1.0` though but.. I will update DEV version 0.0.8 with the latest stable.

**Comment by obastemur** [comment]
It's part of the initial 0.0.8 release now. BTW (jxcore-cordova Changelog is always current)
