### ISSUE TITLE
Can you help me build app for Android?

### ISSUE THREAD

**Issue by bugagarep** [jxcore/jxcore-cordova#83]
Hi, I work with VS 2015 and Cordova on windows 8.1 and try create app with _jxcore-cordova_.
When  I try run app on emulator or device catch error:
**Failed to install 'io.jxcore.node':Error Uh oh!
"D:\code\cordova\MyApp\plugins\io.jxcore.node\src\android\libs\armeabi" not found!**

Do you know how it fix?

**Comment by obastemur** [comment]
@bugagarep Looks like you've installed from this repository. Please follow the steps from https://github.com/jxcore/jxcore-cordova-release

**Comment by bugagarep** [comment]
Thanks
