### ISSUE TITLE
jxcore stopped working on android 6.0 marshmallow

### ISSUE THREAD

**Issue by dortamiguel** [jxcore/jxcore-cordova#87]
I created a blank project and followed all the steps in this repo for installig the samples. When I run them in an Adroid 5.0 version or in iOS the app loas perfectly but when I try in my Nexus 5 with android 6.0 I get an error.

The following image shows what I get.

![yep](https://cloud.githubusercontent.com/assets/3449006/10710955/5c81076e-7a64-11e5-96c4-e6017b62daa9.png)

How I can fix this?

**Comment by ktrzeciaknubisa** [comment]
I see it on [jxcore-cordova-release 0.0.7](https://github.com/jxcore/jxcore-cordova-release/tree/master/0.0.7).

**Comment by dortamiguel** [comment]
Yes,  same result also on 0.0.8

**Comment by dortamiguel** [comment]
I think this error is because they changed on android 6.0 something related with the system apps... I dunno

**Comment by jyang** [comment]
I see the same issue with Cordova 5.3.3 and jxcore-cordova 0.0.8.

**Comment by ktrzeciaknubisa** [comment]
This is also fixed with a94bb7f3c460bd3f80da75bb7b52754068583472 and available in jxcore-cordova 0.0.8 binaries package.
