### ISSUE TITLE
Universal Windows Platform in jxcore-cordova plugin

### ISSUE THREAD

**Issue by cdynak** [jxcore/jxcore-cordova#92]
I've seen, that there are some announcements about adding support for Universal Windows Platform (i.e. on http://jxcore.com), but can't find anything about that or Chakra in code. I'm very interested in supporting this project and possibly use it in quite large application, that I'm currently developing in node.js. What are the plans about releasing jxcore-cordova with UWP (days/weeks/months?) and is there a chance to get some beta code for testing?

**Comment by obastemur** [comment]
@cdynak the work is going on under 0.3.1.0 branch. It's aprox. couple of weeks away from a release.

**Comment by cdynak** [comment]
Thank you very much for quick answer. I'll try to set up environment with Chakra.
