### ISSUE TITLE
'ENOENT, no such file or directory' error on Android M

### ISSUE THREAD

**Issue by dortamiguel** [jxcore/jxcore-cordova#93]
Hi, now almost everything is working fine for me in android M but I have some problems with the following piece of code:

```
var connect = require('connect'),
directory = './static/';

connect().use(connect.static(directory)).listen(8888);
clog('http server listening on port 8888');
```

I get the follwing error:

![screenshot_20151029-190226](https://cloud.githubusercontent.com/assets/3449006/10829203/90d3627c-7e70-11e5-8627-48fa8e6fae4b.png)

I think that is caused by the line that says 'directory = './static/';', is this my fault because I'm setting wrong the directory?

**Comment by ktrzeciaknubisa** [comment]
Would you try `path.join(__dirname, "static")` ?

**Comment by dortamiguel** [comment]
I just tried, I get the same error.

**Comment by ktrzeciaknubisa** [comment]
Are you using this [connect](https://github.com/senchalabs/connect) ? Which version? When I run your sample against 3.4.0, I get:

``` bash
connect().use(connect.static(directory)).listen(8888);
                            ^
TypeError: Object function createServer() {
 ...
} has no method 'static'
```

**Comment by dortamiguel** [comment]
Sorry, I was using an older version of connect. I just updated and now I get the same error. Maybe the code that I'm using is too old.

**Comment by ktrzeciaknubisa** [comment]
You get same error as mine, or yours? My error gets raised because apparently they [changed api](https://github.com/senchalabs/connect) :

> `serve-static` - previously `static`

**Comment by dortamiguel** [comment]
So the error was because of my outdated code, now everything is working fine. Thanks.

Now I'm using the following code:

```
// Starts an http-server server
var finalhandler = require('finalhandler')
var http = require('http')
var serveStatic = require('serve-static')

// Serve up public/ftp folder 
var serve = serveStatic('static', {'index': ['index.html', 'index.htm']})

// Create server 
var server = http.createServer(function(req, res){
  var done = finalhandler(req, res)
  serve(req, res, done)
})

// Listen 
server.listen(7777)
```

**Comment by ktrzeciaknubisa** [comment]
Still I'd like to check something. Could you paste the old code and previous connect version number, if you still have it?

**Comment by dortamiguel** [comment]
It was version 2.30.2

And the code was:

```
var connect = require('connect'),
directory = './static/';

connect().use(connect.static(directory)).listen(8888);
clog('http server listening on port 8888');
```

**Comment by ktrzeciaknubisa** [comment]
Thank you. With that version I was able to get same error as yours. This might be a bug, so until I'll trace it, I'm reopening the ticket.

**Comment by ktrzeciaknubisa** [comment]
There was a bug indeed. It's fixed now. Also 0.0.8 binaries package updated. Thanks @ellipticaldoor !
