### ISSUE TITLE
armeabi" already exists!

### ISSUE THREAD

**Issue by sahalswappo** [jxcore/jxcore-cordova#95]
Hello , 

I try to add this plugin but it throw this error:

> Failed to install 'io.jxcore.node':Error: Uh oh!
> "/home/caal/ifca/exec/platforms/android/libs/armeabi" already exists!
>     at Object.module.exports.common.copyNewFile (/home/caal/.nvm/versions/node/v0.12.4/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:67:19)
>     at Object.module.exports.source-file.install (/home/caal/.nvm/versions/node/v0.12.4/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:78:20)
>     at installWrapper (/home/caal/.nvm/versions/node/v0.12.4/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/platforms.js:77:32)
>     at Object.ActionStack.process (/home/caal/.nvm/versions/node/v0.12.4/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:68:25)
>     at handleInstall (/home/caal/.nvm/versions/node/v0.12.4/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:576:20)
>     at /home/caal/.nvm/versions/node/v0.12.4/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:363:28
>     at _fulfilled (/home/caal/.nvm/versions/node/v0.12.4/lib/node_modules/cordova/node_modules/q/q.js:787:54)
>     at self.promiseDispatch.done (/home/caal/.nvm/versions/node/v0.12.4/lib/node_modules/cordova/node_modules/q/q.js:816:30)
>     at Promise.promise.promiseDispatch (/home/caal/.nvm/versions/node/v0.12.4/lib/node_modules/cordova/node_modules/q/q.js:749:13)
>     at /home/caal/.nvm/versions/node/v0.12.4/lib/node_modules/cordova/node_modules/q/q.js:509:49

How can I fix this ?

**Comment by ktrzeciaknubisa** [comment]
@sahalswappo Problem solved?

**Comment by sahalswappo** [comment]
@ktrzeciaknubisa no . I thought I does . Once I remove and try to add platform it happens again .

**Comment by ktrzeciaknubisa** [comment]
Do you have any other plugins added that may use _platforms/android/libs/armeabi_ folder? I mean, does the folder really exists before you add jxcore-cordova plugin?

**Comment by sahalswappo** [comment]
com.ios.infoplistconfig 0.1.0 "iOS Info Plist"
cordova-plugin-device 1.0.2-dev "Device"
cordova-plugin-file 3.0.0 "File"
cordova-plugin-whitelist 1.0.0 "Whitelist"
cordova-sqlite-storage 0.7.11 "Cordova sqlite storage plugin"
hu.dpal.phonegap.plugins.SpinnerDialog 1.3.1 "SpinnerDialog"
nl.x-services.plugins.insomnia 4.0.1 "Insomnia (prevent screen sleep)"
nl.x-services.plugins.socialsharing 4.3.19 "SocialSharing"
nl.x-services.plugins.toast 2.1.1 "Toast"
org.apache.cordova.crashlytics 0.0.2-dev "Crashlytics"
org.apache.cordova.dialogs 0.3.0 "Notification"
org.apache.cordova.network-information 0.2.15 "Network Information"
org.apache.cordova.splashscreen 1.0.0 "Splashscreen"
org.beuckman.geocoder 0.1.0 "Geocoder"

Here list of plugin that I use . Yeah . The folder exist with this file libsqlc-native-driver.so

so this plugin conflict with sqlite plugin ?

**Comment by obastemur** [comment]
@sahalswappo yes. JXcore comes with sqlite builtin. However there is a build option that helps you to keep sqlite out. (https://github.com/jxcore/jxcore/blob/master/doc/HOW_TO_COMPILE.md)
